# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'gui_calc.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(400, 300)
        self.addButton = QtWidgets.QPushButton(Dialog)
        self.addButton.setGeometry(QtCore.QRect(60, 70, 75, 23))
        self.addButton.setObjectName("addButton")
        self.subtractButton = QtWidgets.QPushButton(Dialog)
        self.subtractButton.setGeometry(QtCore.QRect(60, 100, 75, 23))
        self.subtractButton.setObjectName("subtractButton")
        self.multiplicationButton = QtWidgets.QPushButton(Dialog)
        self.multiplicationButton.setGeometry(QtCore.QRect(60, 130, 75, 23))
        self.multiplicationButton.setObjectName("multiplicationButton")
        self.divisionButton = QtWidgets.QPushButton(Dialog)
        self.divisionButton.setGeometry(QtCore.QRect(60, 160, 75, 23))
        self.divisionButton.setObjectName("divisionButton")
        self.oneButton = QtWidgets.QPushButton(Dialog)
        self.oneButton.setGeometry(QtCore.QRect(190, 70, 31, 23))
        self.oneButton.setObjectName("oneButton")
        self.twoButton = QtWidgets.QPushButton(Dialog)
        self.twoButton.setGeometry(QtCore.QRect(230, 70, 31, 23))
        self.twoButton.setObjectName("twoButton")
        self.threeButton = QtWidgets.QPushButton(Dialog)
        self.threeButton.setGeometry(QtCore.QRect(270, 70, 31, 23))
        self.threeButton.setObjectName("threeButton")
        self.fiveButton = QtWidgets.QPushButton(Dialog)
        self.fiveButton.setGeometry(QtCore.QRect(230, 100, 31, 23))
        self.fiveButton.setObjectName("fiveButton")
        self.fourButton = QtWidgets.QPushButton(Dialog)
        self.fourButton.setGeometry(QtCore.QRect(190, 100, 31, 23))
        self.fourButton.setObjectName("fourButton")
        self.sixButton = QtWidgets.QPushButton(Dialog)
        self.sixButton.setGeometry(QtCore.QRect(270, 100, 31, 23))
        self.sixButton.setObjectName("sixButton")
        self.eightButton = QtWidgets.QPushButton(Dialog)
        self.eightButton.setGeometry(QtCore.QRect(230, 130, 31, 23))
        self.eightButton.setObjectName("eightButton")
        self.sevenButton = QtWidgets.QPushButton(Dialog)
        self.sevenButton.setGeometry(QtCore.QRect(190, 130, 31, 23))
        self.sevenButton.setObjectName("sevenButton")
        self.nineButton = QtWidgets.QPushButton(Dialog)
        self.nineButton.setGeometry(QtCore.QRect(270, 130, 31, 23))
        self.nineButton.setObjectName("nineButton")
        self.zeroButton = QtWidgets.QPushButton(Dialog)
        self.zeroButton.setGeometry(QtCore.QRect(230, 160, 31, 23))
        self.zeroButton.setObjectName("zeroButton")
        self.textEdit = QtWidgets.QTextEdit(Dialog)
        self.textEdit.setGeometry(QtCore.QRect(60, 20, 61, 31))
        self.textEdit.setObjectName("textEdit")
        self.textEdit_2 = QtWidgets.QTextEdit(Dialog)
        self.textEdit_2.setGeometry(QtCore.QRect(140, 20, 61, 31))
        self.textEdit_2.setObjectName("textEdit_2")
        self.label = QtWidgets.QLabel(Dialog)
        self.label.setGeometry(QtCore.QRect(300, 20, 71, 21))
        self.label.setObjectName("label")
        self.equalsButton = QtWidgets.QPushButton(Dialog)
        self.equalsButton.setGeometry(QtCore.QRect(60, 190, 75, 23))
        self.equalsButton.setObjectName("equalsButton")

        self.retranslateUi(Dialog)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Dialog"))
        self.addButton.setText(_translate("Dialog", "+"))
        self.subtractButton.setText(_translate("Dialog", "-"))
        self.multiplicationButton.setText(_translate("Dialog", "*"))
        self.divisionButton.setText(_translate("Dialog", "/"))
        self.oneButton.setText(_translate("Dialog", "1"))
        self.twoButton.setText(_translate("Dialog", "2"))
        self.threeButton.setText(_translate("Dialog", "3"))
        self.fiveButton.setText(_translate("Dialog", "5"))
        self.fourButton.setText(_translate("Dialog", "4"))
        self.sixButton.setText(_translate("Dialog", "6"))
        self.eightButton.setText(_translate("Dialog", "8"))
        self.sevenButton.setText(_translate("Dialog", "7"))
        self.nineButton.setText(_translate("Dialog", "9"))
        self.zeroButton.setText(_translate("Dialog", "0"))
        self.label.setText(_translate("Dialog", "0"))
        self.equalsButton.setText(_translate("Dialog", "="))
    
    def press_it(self, pressed):
	    if pressed == "C":
		    self.outputLabel.setText("0")
	    else:
		    #Check to see if it starts with 0 and delete 0
		    if self.outputLabel.text() == "0":
			    self.outputLabel.setText("")
		    #Concatenate the pressed button with what was there already
		    self.outputLabel.setText(f'{self.outputLabel.text()}{pressed}')

if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Dialog = QtWidgets.QDialog()
    ui = Ui_Dialog()
    ui.setupUi(Dialog)
    Dialog.show()
    sys.exit(app.exec_())
